[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --omit=dev --no-audit --no-fund"]

[phases.build]
cmds = ["echo 'Skipping deploy on build'"]

[start]
cmd = "node src/index.js"
